export const GET_CATEGORY = 'GET_CATEGORY';
export const GET_ALLPRODUCTS = 'GET_ALLPRODUCTS';
export const ADD_TOCARD = 'ADD_TOCARD';
export const DELETE_TOCARD = 'DELETE_TOCARD';
export const SEARCH_PRODUCT = 'SEARCH_PRODUCT';
export const GET_CATEGORY_PRODUCT = 'GET_CATEGORY_PRODUCT';